# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: 	ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 17
      uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: install
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: test
    - uses: borales/actions-yarn@v2.3.0
      with:
        cmd: build

    - name: Deploy to GH Pages 🚀
      uses: JamesIves/github-pages-deploy-action@4.2.5
      with:
        branch: deploy # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.

    - name: Deploy to server
      # You may pin to the exact commit or the version.
      uses: appleboy/scp-action@b476d5806f2a4c1ed5902a87fa91b0623cac7258
      # uses: appleboy/scp-action@v0.0.1
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "dist/"
        target: ${{ secrets.PATH }}
        rm: true
